name: avo_inspector
description: Avo Inspector for Dart. Find out what's wrong with your data. The first step to better analytics governance is knowing what's wrong with your data today.
version: 0.9.9
homepage: https://www.avo.app/inspector

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.12
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:

